import { useEffect, useRef, useState } from 'react';
import { httpsCallable } from 'firebase/functions';
import { functions } from '@/lib/constants/firebase';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Sparkles, Send, ShieldCheck, Clock3 } from 'lucide-react';

type ChatMessage = {
  id: string;
  role: 'user' | 'assistant';
  content: string;
};

const chatWithGoogleAi = httpsCallable(functions, 'chatWithGoogleAi');

const starterMessages: ChatMessage[] = [
  {
    id: 'intro',
    role: 'assistant',
    content:
      "Hi! I'm the Kamanga Stays assistant powered by Google AI. Ask me about listings, bookings, payouts, or how to get started hosting.",
  },
];

const quickPrompts = [
  'What are the payout timelines for hosts?',
  'How do I submit a new property for review?',
  'Help me compare rental vs. sale listings in Lusaka.',
  'What fees are deducted from each booking?',
];

const AiAssistant = () => {
  const { user } = useAuth();
  const { toast } = useToast();
  const [messages, setMessages] = useState<ChatMessage[]>(starterMessages);
  const [input, setInput] = useState('');
  const [isSending, setIsSending] = useState(false);
  const endRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const sendMessage = async (prompt?: string) => {
    const text = (prompt ?? input).trim();
    if (!text || isSending) return;

    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: text,
    };

    const history = [...messages, userMessage];
    setMessages(history);
    setInput('');
    setIsSending(true);

    try {
      const response = await chatWithGoogleAi({
        messages: history.map(({ role, content }) => ({ role, content })),
        context: { topic: 'property-gateway' },
      });
      const replyText = (response.data as any)?.reply || 'Sorry, I did not catch that.';
      const reply: ChatMessage = {
        id: `assistant-${Date.now()}`,
        role: 'assistant',
        content: replyText,
      };
      setMessages((prev) => [...prev, reply]);
    } catch (error: any) {
      const description = error?.message ?? 'Unable to reach the assistant right now.';
      toast({
        title: 'AI chat failed',
        description,
        variant: 'destructive',
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-100 py-12">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8">
        <div className="text-center space-y-3">
          <div className="flex items-center justify-center gap-3">
            <Sparkles className="h-6 w-6 text-primary" />
            <h1 className="text-3xl sm:text-4xl font-bold text-gray-900">Kamanga AI Concierge</h1>
            <Sparkles className="h-6 w-6 text-primary" />
          </div>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Ask questions about bookings, payouts, and hosting on the Zambia Property Gateway. Answers are
            generated by Google AI.
          </p>
          <div className="flex items-center justify-center gap-3 text-xs text-gray-500">
            <Badge variant="secondary" className="bg-primary/10 text-primary">
              Google Gemini
            </Badge>
            <span className="flex items-center gap-1">
              <ShieldCheck className="h-3 w-3" />
              Avoid sharing passwords or sensitive data.
            </span>
            <span className="flex items-center gap-1">
              <Clock3 className="h-3 w-3" />
              Fast, concise answers
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card className="lg:col-span-2 shadow-sm border-slate-100">
            <CardHeader>
              <CardTitle>Chat</CardTitle>
              <CardDescription>Get guidance on using the platform</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="h-[420px] overflow-y-auto rounded-lg border bg-white p-4 space-y-4 shadow-inner">
                {messages.map((message) => (
                  <div
                    key={message.id}
                    className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div
                      className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed shadow-sm ${
                        message.role === 'user'
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-slate-50 text-slate-900 border border-slate-100'
                      }`}
                    >
                      {message.content}
                    </div>
                  </div>
                ))}
                <div ref={endRef} />
              </div>

              <div className="space-y-3">
                <Textarea
                  value={input}
                  onChange={(event) => setInput(event.target.value)}
                  placeholder="Ask about bookings, payouts, or property setup..."
                  rows={3}
                />
                <div className="flex items-center justify-between">
                  <div className="text-xs text-muted-foreground">
                    Signed in as {user?.email || 'guest'} · Answers may be AI-generated
                  </div>
                  <Button
                    onClick={() => sendMessage()}
                    disabled={isSending || input.trim().length === 0}
                  >
                    {isSending ? 'Thinking...' : 'Send'}
                    <Send className="h-4 w-4 ml-2" />
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="shadow-sm border-slate-100">
            <CardHeader>
              <CardTitle>Quick prompts</CardTitle>
              <CardDescription>Try one of these to get started</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3">
              {quickPrompts.map((prompt) => (
                <button
                  key={prompt}
                  onClick={() => sendMessage(prompt)}
                  className="w-full text-left text-sm p-3 rounded-lg border hover:border-primary/50 hover:bg-primary/5 transition-colors"
                  disabled={isSending}
                >
                  {prompt}
                </button>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default AiAssistant;
