// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://niacsnuqtgpmxfbpyatl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5pYWNzbnVxdGdwbXhmYnB5YXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MTQ4NDQsImV4cCI6MjA2NDk5MDg0NH0.cLwSEWaI4lRvM9nba793F3MXqaybuqzDNtz-JpZ7XhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);